[package]
title = "RoWorks Service API"
version = "1.0.0"
description = "API service for RoWorks"
category = "RoWorks"

[dependencies]
"omni.usd" = {}
"roworks.scene.manager" = {}
"roworks.data.import" = {}

[[python.module]]
name = "roworks.service.api"

[python.pipapi]
requirements = [
    "fastapi",
    "uvicorn",
    "python-multipart",
]
use_online_index = true
